name = "Observers"
uuid = "338f10d5-c7f1-4033-a7d1-f9dec39bcaa0"
authors = ["Giacomo Torlai <gttorlai@amazon.com>", "Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.2.3"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
Compat = "4.6.1"
DataFrames = "1.5.0"
julia = "1.6"
