name = "Observers"
uuid = "338f10d5-c7f1-4033-a7d1-f9dec39bcaa0"
authors = ["Giacomo Torlai <gttorlai@amazon.com>", "Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "0.0.1"

[deps]
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
